### PR TITLE
fix .csproj path in CI/Build definition

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Otherwise there is an error at the `Build solution` task:
```
MSBUILD : error MSB1009: Project file does not exist.
```

### CODE REVIEW

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility
Hi Paul, please review & advise.  Can this be merged or does this PR affect other docs?
Thanks, Dawnmarie

**Comment by paulopsgility** [comment]
Because this would be a blocking error and because it has not come up before I'd like to hold this until we can test it.

**Comment by paulopsgility** [comment]
@mathieu-benoit We have a test/fix scheduled for this one very soon. We will verify this then and update here.

**Comment by tylerd** [comment]
This only happens if the participant commits the entire directory to Git, rather than following the instructions and only committing the web project folder to Git.

Many participants skip over the `cd` step and check the whole studentfiles directory into Git

One change that i would propose is more emphasis on this step so they don't make a mistake and have failing builds

**Comment by mathieu-benoit** [comment]
FYI @tylerd, I followed the instructions and did `cd studentfiles` and then the `git push` will push both folders `armtemplates` and `tailspintoysweb` which are needed. So I really think this patch should be applied...

**Comment by tylerd** [comment]
@mathieu-benoit I wonder if it was a different version of the docs

[Exercise 2 - Task 4 - Add the Tailspin Toys source code repository to Azure DevOps](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-2-add-the-tailspin-toys-source-code-repository-to-azure-devops)

In this Task, you will configure the Azure DevOps Git repository. You will configure the remote repository using Git and then push the source code up to Azure DevOps through the command line tools.

1. Open the *Azure Cloud Shell* to the folder where the Student Files were unzipped (e.g. studentfiles). Then, navigate to the **tailspintoysweb** folder which contains the source code for our web application.

...

3. In *Azure Cloud Shell*, initialize a local Git repository by running the following command:

    > If a ".git" folder and local repository already exists in the folder, then you will need to delete the ".git" folder first before running the commands below to initialize the Git repository.

    ```bash
    git init
    ```

**Comment by tylerd** [comment]
I wonder if the fix could use a wildcard search for any .csproj files?

**Comment by mathieu-benoit** [comment]
Yep that's a good point, `**/*.csproj` could do the job... I will test it and update this PR accordingly.

**Comment by mathieu-benoit** [comment]
And you are right @tylerd I misread the instructions apparently ;) But 50% of the 60 participants I got last week did too. So maybe to avoid any subfolder or sub-subfolder issue, I just changed this PR to be more generic on that regard with `**/tailspintoysweb.csproj`.

**Comment by paulopsgility** [comment]
This was resolved in the March 2020 test/fix

**Pull request closed without merging**
